export default {
    // private
    dashboard: '/dashboard',
    overview: '/overview',
    overviewTwo: '/overview/two',
    overviewThree: '/overview/three',
    tickets: '/tickets',
    ideas: '/ideas',
    ideasTwo: '/ideas/two',
    ideasThree: '/ideas/three',
    contacts: '/contacts',
    agents: '/agents',
    articles: '/articles',
    settings: '/settings',
    subscription: '/subscription',
    deas: '/deas',
    deasTwo: '/deas/two',
    deasThree: '/deas/three',
    deasFour: '/deas/four',
    deasFive: '/deas/five',
    deasSix: '/deas/six',
    hardwOne: '/hardw/one',
    hardwTwo: '/hardw/two',
    hardwThree: '/hardw/three',
    hardwFour: '/hardw/four',
    hardwFive: '/hardw/five',
    hardwSix: '/hardw/six',
    hardwSeven: '/hardw/seven',
    hardwEight: '/hardw/eight',
    hardwNine: '/hardw/nine',
    hardwTen: '/hardw/ten',
    hardwEleven: '/hardw/eleven',
    hardwTwelve: '/hardw/twelve',

    hardwfOne: '/hardwf/one',
    hardwfTwo: '/hardwf/two',
    hardwfThree: '/hardwf/three',
    hardwfbOne: '/hardwfb/one',
    hardwfbTwo: '/hardwfb/two',
    docOne:'/doc/one',
    docTwo:'/doc/two',
    docThree:'/doc/three',
    docFour:'/doc/four',
    docFive:'/doc/five',
    docSix:'/doc/six',
    docSeven:'/doc/seven',
    docEight:'/doc/eight',
    docNine:'/doc/nine',
    softOne: '/soft/one',
    softTwo: '/soft/two',
    softThree: '/soft/three',
    softFour: '/soft/four',
    softFive: '/soft/five',
    softSix: '/soft/six',




    softwOne: '/softw/one',
    softwTwo: '/softw/two',
    softwThree: '/softw/three',
    softwFour: '/softw/four',
    softwFive: '/softw/five',
    softwSix: '/softw/six',
    softwSeven: '/softw/seven',
    softwEight: '/softw/eight',
    softwNine: '/softw/nine',
    softwTen: '/softw/ten',
    softwEleven: '/softw/eleven',
    softwTwelve: '/softw/twelve',
    softwThirteen: '/softw/thirteen',
    wardOne: '/ward/one',
    wardTwo: '/ward/two',
    wardThree: '/ward/three',
    kazOne: '/kaz/one',
    kazTwo: '/kaz/two',
    kazThree: '/kaz/three',
    kazFour: '/kaz/four',
    kazFive: '/kaz/five',
    kazSix: '/kaz/six',
    inspOne: '/insp/one',
    inspTwo: '/insp/two',
    inspThree: '/insp/three',
    inspFour: '/insp/four',
    javaOne: '/java/one',
    javaTwo: '/java/two',
    javaThree: '/java/three',

    onbotOne: '/onbot/one',
    onbotTwo: '/onbot/two',
    onbotThree: '/onbot/three',

    interOne: '/inter/one',
    interTwo: '/inter/two',
    interThree: '/inter/three',







    // auth
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgot_password'
};
